### ISSUE TITLE
Create Events page Template

### ISSUE THREAD

**Issue by Im-Abhi** [ieeecompsoc/IEEE-MSIT-MERN#3]
- should match the UI provided to you
- create basic HTML +  CSS page which can be later used in react.

**Comment by anujjha13** [comment]
![IEEE_white 1logo](https://user-images.githubusercontent.com/56735384/167288916-e9ccdb70-721b-47be-9f17-bc6c8b0fcbab.jpeg)

**Comment by anujjha13** [comment]
![IEEE_white 1logo](https://user-images.githubusercontent.com/56735384/167288955-e2c61d63-1ebd-4856-989a-3f9353dfa295.jpeg)
events page created.

**Comment by Im-Abhi** [comment]
@anujjha13 create a new folder in client/htmlFiles/Events and add your html and css files there and mention this issue when creating a PR
